export type Lesson={id:string;module:string;title:string;minutes:number;content:string;videoUrl?:string};
export type Course={id:string;title:string;description:string;category:string;price:number;status:string;accent:string;instructor:string;lessons:Lesson[];createdAt:string};
export type Order={id:string;courseId:string;name:string;email:string;country:string;source:string;method:string;amount:number;status:string;createdAt:string;isDemo:number};
export type Enrollment={id:string;courseId:string;name:string;email:string;learnerId:string|null;createdAt:string};
export type Snapshot={courses:Course[];orders:Order[];enrollments:Enrollment[];progress:{enrollmentId:string;lessonId:string}[];settings:{name:string;description:string};user:{name:string;email:string;id:string}};
export const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
export const categories=["Marketing","Tecnologia","Design","Negócios","Desenvolvimento pessoal"];
export const sampleCourses:Course[]=[
 {id:"marketing",title:"Marketing Digital do Zero",description:"Construa uma presença digital com estratégia. Aprenda a definir seu público, criar conteúdo que conecta e estruturar seu primeiro funil de vendas.",category:"Marketing",price:49700,status:"Publicado",accent:"orange",instructor:"Equipe Arceuz",createdAt:"2026-09-01T12:00:00Z",lessons:[
 {id:"m1",module:"01 • Fundamentos",title:"Comece pela sua audiência",minutes:12,content:"Uma estratégia começa com uma pessoa real. Liste os problemas que seu público enfrenta, as soluções que já tentou e o resultado que deseja alcançar.\n\nExercício: entreviste três pessoas do seu público. Pergunte qual é a maior dificuldade atual e registre as palavras que elas usam.\n\nSua entrega: uma descrição do público em três frases, com contexto, problema e objetivo."},
 {id:"m2",module:"01 • Fundamentos",title:"Sua proposta de valor",minutes:16,content:"A proposta de valor conecta um problema específico a um resultado desejado. Escreva: eu ajudo [público] a [resultado] por meio de [método].\n\nEvite promessas genéricas. Mostre o que o aluno conseguirá fazer ao concluir seu curso.\n\nExercício: escreva três versões e escolha a mais clara. Valide a frase com uma pessoa do seu público."},
 {id:"m3",module:"02 • Conteúdo e conversão",title:"Crie um calendário de conteúdo",minutes:18,content:"Organize seu conteúdo em três objetivos: atrair, ensinar e apresentar sua oferta. Escolha um canal principal para começar.\n\nPlaneje uma semana com dois conteúdos educativos, um estudo de caso e uma apresentação do seu curso.\n\nExercício: crie títulos e uma chamada para cada publicação. Defina a ação esperada do leitor."},
 {id:"m4",module:"02 • Conteúdo e conversão",title:"Estruture seu primeiro funil",minutes:21,content:"Um funil conecta descoberta, interesse e decisão. Sua mensagem precisa acompanhar a etapa em que a pessoa está.\n\nMapeie o caminho: conteúdo → página do curso → checkout → boas-vindas. Verifique se cada etapa responde à principal dúvida do visitante.\n\nProjeto final: desenhe esse caminho para seu produto e identifique uma melhoria em cada etapa."}]},
 {id:"inteligencia",title:"Inteligência Artificial na Prática",description:"Use inteligência artificial para organizar ideias, melhorar processos e criar entregas com mais clareza. Um curso prático para o seu dia a dia.",category:"Tecnologia",price:69700,status:"Publicado",accent:"black",instructor:"Equipe Arceuz",createdAt:"2026-09-02T12:00:00Z",lessons:[
 {id:"i1",module:"01 • Primeiros passos",title:"Defina uma tarefa com clareza",minutes:14,content:"Antes de pedir uma resposta, defina o resultado esperado. Inclua contexto, objetivo, formato e restrições.\n\nExercício: escolha uma tarefa recorrente e escreva um pedido com esses quatro elementos. Compare o resultado com um pedido sem contexto."},
 {id:"i2",module:"01 • Primeiros passos",title:"Revise e refine os resultados",minutes:17,content:"Uma resposta inicial é um ponto de partida. Verifique fatos, premissas, omissões e se o formato atende ao objetivo.\n\nExercício: peça duas alternativas para uma entrega e compare-as usando critérios explícitos: clareza, precisão e utilidade."},
 {id:"i3",module:"02 • Aplicação",title:"Monte seu fluxo de trabalho",minutes:22,content:"Divida um processo em entrada, execução, revisão e entrega. Identifique onde a IA pode ajudar e onde uma verificação humana é necessária.\n\nProjeto final: documente um fluxo reutilizável com um exemplo de entrada e uma lista de critérios para aprovar a saída."}]},
 {id:"design",title:"Design que Vende",description:"Transforme sua comunicação visual. Aprenda hierarquia, tipografia e composição para criar páginas e materiais que deixam sua oferta mais clara.",category:"Design",price:39700,status:"Publicado",accent:"neutral",instructor:"Equipe Arceuz",createdAt:"2026-09-03T12:00:00Z",lessons:[
 {id:"d1",module:"01 • Composição",title:"Hierarquia visual na prática",minutes:15,content:"Dê prioridade ao que precisa ser visto primeiro. Use tamanho, contraste, alinhamento e espaço para guiar a leitura.\n\nExercício: reorganize uma peça com um título principal, um texto de apoio e uma ação. Remova elementos que competem com a mensagem."},
 {id:"d2",module:"01 • Composição",title:"Tipografia e legibilidade",minutes:18,content:"Escolha fontes legíveis e use poucas variações. Teste sua peça em telas pequenas e com ampliação.\n\nExercício: crie uma escala de título, subtítulo, corpo e legenda. Confira se a hierarquia permanece clara sem depender apenas de cores."},
 {id:"d3",module:"02 • Projeto",title:"Sua página de oferta",minutes:24,content:"Uma página de oferta responde: para quem é, que resultado entrega, o que está incluído e qual é o próximo passo.\n\nProjeto final: organize essas informações e revise a página com alguém que ainda não conhece seu produto."}]},
 {id:"negocios",title:"Negócios Digitais: do Plano à Ação",description:"Organize seu modelo de negócio, transforme ideias em uma oferta e prepare um plano de lançamento com metas e tarefas claras.",category:"Negócios",price:89700,status:"Rascunho",accent:"orange",instructor:"Equipe Arceuz",createdAt:"2026-09-04T12:00:00Z",lessons:[{id:"n1",module:"01 • Planejamento",title:"Seu modelo de negócio",minutes:20,content:"Defina o público, a proposta de valor, os canais de venda e os principais custos.\n\nExercício: escreva uma hipótese para cada item e escolha quais você precisa validar primeiro."}]}
];
